apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    finalizers:
    - kubernetes.io/pv-protection
    name: PROJECT9-APPLE9-app-pv 
  spec: 
    accessModes:
    - ReadWriteMany
    capacity:
      storage: 5Gi
    nfs:
      path: /data/nfs/app-pv/PROJECT9/APPLE9/app/
      server: 10.65.40.90
    persistentVolumeReclaimPolicy: Retain
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    finalizers:
    - kubernetes.io/pv-protection
    name: PROJECT9-APPLE9-logs-pv
  spec:
    accessModes:
    - ReadWriteMany
    capacity:
      storage: 5Gi
    nfs:
      path: /storage/nfs/PROJECT9/APPLE9/logs/
      server: 10.65.40.90
    persistentVolumeReclaimPolicy: Retain
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    namespace: PROJECT9
    annotations:
    finalizers:
    - kubernetes.io/pvc-protection
    name: PROJECT9-APPLE9-app-pvc
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 5Gi
    volumeName: PROJECT9-APPLE9-app-pv
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    namespace: PROJECT9
    annotations:
    finalizers:
    - kubernetes.io/pvc-protection
    name: PROJECT9-APPLE9-logs-pvc
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 5Gi
    volumeName: PROJECT9-APPLE9-logs-pv
kind: List
