apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    finalizers:
    - kubernetes.io/pv-protection
    name: wspark-sample-httpd-eap73-was-app-pv 
  spec: 
    accessModes:
    - ReadWriteMany
    capacity:
      storage: 5Gi
    nfs:
      path: /data/nfs/app-pv/wspark/sample-httpd-eap73/was-app/
      server: 10.65.40.90
    persistentVolumeReclaimPolicy: Retain
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    finalizers:
    - kubernetes.io/pv-protection
    name: wspark-sample-httpd-eap73-web-logs-pv
  spec:
    accessModes:
    - ReadWriteMany
    capacity:
      storage: 5Gi
    nfs:
      path: /storage/nfs/wspark/sample-httpd-eap73/web-logs/
      server: 10.65.40.90
    persistentVolumeReclaimPolicy: Retain
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    finalizers:
    - kubernetes.io/pv-protection
    name: wspark-sample-httpd-eap73-was-logs-pv
  spec:
    accessModes:
    - ReadWriteMany
    capacity:
      storage: 5Gi
    nfs:
      path: /storage/nfs/wspark/sample-httpd-eap73/was-logs/
      server: 10.65.40.90
    persistentVolumeReclaimPolicy: Retain
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    namespace: wspark
    annotations:
    finalizers:
    - kubernetes.io/pvc-protection
    name: wspark-sample-httpd-eap73-was-app-pvc
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 5Gi
    volumeName: wspark-sample-httpd-eap73-was-app-pv
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    namespace: wspark
    annotations:
    finalizers:
    - kubernetes.io/pvc-protection
    name: wspark-sample-httpd-eap73-was-logs-pvc
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 5Gi
    volumeName: wspark-sample-httpd-eap73-was-logs-pv
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    namespace: wspark
    annotations:
    finalizers:
    - kubernetes.io/pvc-protection
    name: wspark-sample-httpd-eap73-web-logs-pvc
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 5Gi
    volumeName: wspark-sample-httpd-eap73-web-logs-pv

kind: List
